CREATE OR REPLACE DATABASE DEMO_DB;
USE DATABASE DEMO_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA FEATURE_STORE;
CREATE OR REPLACE SCHEMA ML;

-- customers
CREATE OR REPLACE TABLE RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR PRIMARY KEY,
  SIGNUP_DATE DATE,
  COUNTRY VARCHAR,
  IS_PREMIUM BOOLEAN
);

-- transactions
CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TX_ID VARCHAR PRIMARY KEY,
  CUSTOMER_ID VARCHAR,
  TX_AMOUNT NUMBER(12,2),
  TX_TS TIMESTAMP_NTZ
);

INSERT INTO RAW.CUSTOMERS (CUSTOMER_ID, SIGNUP_DATE, COUNTRY, IS_PREMIUM) VALUES
('C001','2024-01-15','IN', TRUE),
('C002','2024-03-02','US', FALSE),
('C003','2023-11-20','IN', FALSE),
('C004','2024-06-10','GB', TRUE);

INSERT INTO RAW.TRANSACTIONS (TX_ID, CUSTOMER_ID, TX_AMOUNT, TX_TS) VALUES
('T001','C001', 1200.00, '2024-11-01 10:15:00'),
('T002','C001', 75.50,   '2024-11-20 18:00:00'),
('T003','C002', 15.00,   '2024-10-05 09:30:00'),
('T004','C003', 200.00,  '2024-11-15 12:01:00'),
('T005','C001', 40.00,   '2024-12-01 08:10:00'),
('T006','C002', 500.00,  '2024-12-03 11:20:00'),
('T007','C004', 75.00,   '2024-12-02 20:45:00');


CREATE OR REPLACE TABLE FEATURE_STORE.FEATURE_REGISTRY (
  FEATURE_NAME VARCHAR PRIMARY KEY,
  FEATURE_TABLE VARCHAR,        -- table where feature lives (schema.table)
  FEATURE_COLUMN VARCHAR,       -- column name in that table
  DESCRIPTION VARCHAR,
  CREATION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  OWNER VARCHAR
);

CREATE OR REPLACE TABLE FEATURE_STORE.CUSTOMER_FEATURES (
  FEATURE_DATE DATE,
  CUSTOMER_ID VARCHAR,
  TX_COUNT_30D NUMBER,
  TX_SUM_30D NUMBER(18,2),
  TX_AVG_30D NUMBER(18,2),
  TX_COUNT_90D NUMBER,
  DAYS_SINCE_LAST_TX NUMBER,
  IS_ACTIVE_30D BOOLEAN,
  COUNTRY_TX_COUNT NUMBER,
  SIGNUP_AGE_DAYS NUMBER,
  IS_PREMIUM BOOLEAN,
  COUNTRY VARCHAR,
  PRIMARY KEY (FEATURE_DATE, CUSTOMER_ID)
);

-- 1) Set the feature date (snapshot date)
SET AS_OF_DATE = CURRENT_DATE();

-- 2) Insert features for that snapshot into the feature table
INSERT INTO FEATURE_STORE.CUSTOMER_FEATURES
(
  FEATURE_DATE,
  CUSTOMER_ID,
  TX_COUNT_30D,
  TX_SUM_30D,
  TX_AVG_30D,
  TX_COUNT_90D,
  DAYS_SINCE_LAST_TX,
  IS_ACTIVE_30D,
  COUNTRY_TX_COUNT,
  SIGNUP_AGE_DAYS,
  IS_PREMIUM,
  COUNTRY
)
WITH tx_agg AS (
  SELECT
    c.CUSTOMER_ID,
    -- transactions in last 30 days
    COALESCE(SUM(
      CASE WHEN t.TX_TS >= DATEADD(day, -30, $AS_OF_DATE::DATE) THEN 1 ELSE 0 END
    ), 0) AS TX_COUNT_30D,

    COALESCE(SUM(
      CASE WHEN t.TX_TS >= DATEADD(day, -30, $AS_OF_DATE::DATE) THEN t.TX_AMOUNT ELSE 0 END
    ), 0) AS TX_SUM_30D,

    -- transactions in last 90 days
    COALESCE(SUM(
      CASE WHEN t.TX_TS >= DATEADD(day, -90, $AS_OF_DATE::DATE) THEN 1 ELSE 0 END
    ), 0) AS TX_COUNT_90D,

    -- last transaction timestamp for the customer
    MAX(t.TX_TS) AS LAST_TX_TS
  FROM RAW.CUSTOMERS c
  LEFT JOIN RAW.TRANSACTIONS t
    ON c.CUSTOMER_ID = t.CUSTOMER_ID
  GROUP BY c.CUSTOMER_ID
),
country_counts AS (
  SELECT
    COUNTRY,
    COUNT(*) AS COUNTRY_COUNT
  FROM RAW.CUSTOMERS
  GROUP BY COUNTRY
)
SELECT
  $AS_OF_DATE::DATE AS FEATURE_DATE,
  c.CUSTOMER_ID,

  -- counts & sums directly from the aggregated CTE
  COALESCE(a.TX_COUNT_30D, 0) AS TX_COUNT_30D,
  COALESCE(a.TX_SUM_30D, 0) AS TX_SUM_30D,

  -- average amount in last 30 days
  CASE
    WHEN COALESCE(a.TX_COUNT_30D, 0) = 0 THEN 0
    ELSE a.TX_SUM_30D / a.TX_COUNT_30D
  END AS TX_AVG_30D,

  COALESCE(a.TX_COUNT_90D, 0) AS TX_COUNT_90D,

  -- days since last transaction
  CASE
    WHEN a.LAST_TX_TS IS NULL THEN NULL
    ELSE DATEDIFF('day', a.LAST_TX_TS, $AS_OF_DATE::DATE)
  END AS DAYS_SINCE_LAST_TX,

  -- activity flag: any transaction in last 30 days?
  CASE
    WHEN a.LAST_TX_TS IS NOT NULL
         AND a.LAST_TX_TS >= DATEADD(day, -30, $AS_OF_DATE::DATE)
    THEN TRUE
    ELSE FALSE
  END AS IS_ACTIVE_30D,

  COALESCE(cc.COUNTRY_COUNT, 0) AS COUNTRY_TX_COUNT,

  -- days since signup
  DATEDIFF('day', c.SIGNUP_DATE, $AS_OF_DATE::DATE) AS SIGNUP_AGE_DAYS,

  c.IS_PREMIUM,
  c.COUNTRY
FROM RAW.CUSTOMERS c
LEFT JOIN tx_agg a
  ON c.CUSTOMER_ID = a.CUSTOMER_ID
LEFT JOIN country_counts cc
  ON c.COUNTRY = cc.COUNTRY;

INSERT INTO FEATURE_STORE.FEATURE_REGISTRY (FEATURE_NAME, FEATURE_TABLE, FEATURE_COLUMN, DESCRIPTION, OWNER)
VALUES
('tx_count_30d', 'FEATURE_STORE.CUSTOMER_FEATURES', 'TX_COUNT_30D', 'Number of transactions in 30 days prior to FEATURE_DATE', 'you@example.com'),
('tx_sum_30d', 'FEATURE_STORE.CUSTOMER_FEATURES', 'TX_SUM_30D', 'Total spend in 30 days prior to FEATURE_DATE', 'you@example.com'),
('tx_avg_30d', 'FEATURE_STORE.CUSTOMER_FEATURES', 'TX_AVG_30D', 'Average transaction amount in 30 days prior to FEATURE_DATE', 'you@example.com'),
('tx_count_90d', 'FEATURE_STORE.CUSTOMER_FEATURES', 'TX_COUNT_90D', 'Number of transactions in 90 days prior to FEATURE_DATE', 'you@example.com'),
('days_since_last_tx', 'FEATURE_STORE.CUSTOMER_FEATURES', 'DAYS_SINCE_LAST_TX', 'Days since last transaction as of FEATURE_DATE', 'you@example.com'),
('is_active_30d', 'FEATURE_STORE.CUSTOMER_FEATURES', 'IS_ACTIVE_30D', 'Boolean flag: had any transactions in last 30 days', 'you@example.com'),
('country_tx_count', 'FEATURE_STORE.CUSTOMER_FEATURES', 'COUNTRY_TX_COUNT', 'Number of customers from the same country (proxy for frequency)', 'you@example.com'),
('signup_age_days', 'FEATURE_STORE.CUSTOMER_FEATURES', 'SIGNUP_AGE_DAYS', 'Days since signup as of FEATURE_DATE', 'you@example.com');


CREATE OR REPLACE STREAM RAW.TRANSACTIONS_STREAM ON TABLE RAW.TRANSACTIONS APPEND_ONLY = FALSE;

SHOW WAREHOUSES;

CREATE OR REPLACE TASK FEATURE_STORE.DAILY_MATERIALIZE
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 1 * * * UTC'
AS
BEGIN
  -- delete today's snapshot if it already exists (idempotent)
  DELETE FROM FEATURE_STORE.CUSTOMER_FEATURES
  WHERE FEATURE_DATE = CURRENT_DATE();

  -- insert today's snapshot
  INSERT INTO FEATURE_STORE.CUSTOMER_FEATURES
  (
    FEATURE_DATE,
    CUSTOMER_ID,
    TX_COUNT_30D,
    TX_SUM_30D,
    TX_AVG_30D,
    TX_COUNT_90D,
    DAYS_SINCE_LAST_TX,
    IS_ACTIVE_30D,
    COUNTRY_TX_COUNT,
    SIGNUP_AGE_DAYS,
    IS_PREMIUM,
    COUNTRY
  )
  WITH tx_agg AS (
    SELECT
      c.CUSTOMER_ID,
      COALESCE(SUM(
        CASE WHEN t.TX_TS >= DATEADD(day, -30, CURRENT_DATE()) THEN 1 ELSE 0 END
      ), 0) AS TX_COUNT_30D,

      COALESCE(SUM(
        CASE WHEN t.TX_TS >= DATEADD(day, -30, CURRENT_DATE()) THEN t.TX_AMOUNT ELSE 0 END
      ), 0) AS TX_SUM_30D,

      COALESCE(SUM(
        CASE WHEN t.TX_TS >= DATEADD(day, -90, CURRENT_DATE()) THEN 1 ELSE 0 END
      ), 0) AS TX_COUNT_90D,

      MAX(t.TX_TS) AS LAST_TX_TS
    FROM RAW.CUSTOMERS c
    LEFT JOIN RAW.TRANSACTIONS t
      ON c.CUSTOMER_ID = t.CUSTOMER_ID
    GROUP BY c.CUSTOMER_ID
  ),
  country_counts AS (
    SELECT
      COUNTRY,
      COUNT(*) AS COUNTRY_COUNT
    FROM RAW.CUSTOMERS
    GROUP BY COUNTRY
  )
  SELECT
    CURRENT_DATE() AS FEATURE_DATE,
    c.CUSTOMER_ID,
    a.TX_COUNT_30D,
    a.TX_SUM_30D,
    CASE
      WHEN a.TX_COUNT_30D = 0 THEN 0
      ELSE a.TX_SUM_30D / a.TX_COUNT_30D
    END AS TX_AVG_30D,
    a.TX_COUNT_90D,
    CASE
      WHEN a.LAST_TX_TS IS NULL THEN NULL
      ELSE DATEDIFF('day', a.LAST_TX_TS, CURRENT_DATE())
    END AS DAYS_SINCE_LAST_TX,
    CASE
      WHEN a.LAST_TX_TS >= DATEADD(day, -30, CURRENT_DATE()) THEN TRUE
      ELSE FALSE
    END AS IS_ACTIVE_30D,
    COALESCE(cc.COUNTRY_COUNT, 0) AS COUNTRY_TX_COUNT,
    DATEDIFF('day', c.SIGNUP_DATE, CURRENT_DATE()) AS SIGNUP_AGE_DAYS,
    c.IS_PREMIUM,
    c.COUNTRY
  FROM RAW.CUSTOMERS c
  LEFT JOIN tx_agg a
    ON c.CUSTOMER_ID = a.CUSTOMER_ID
  LEFT JOIN country_counts cc
    ON c.COUNTRY = cc.COUNTRY;
END;

ALTER TASK FEATURE_STORE.DAILY_MATERIALIZE RESUME;
SHOW TASKS IN SCHEMA FEATURE_STORE;

-- Create outcome table: did customer churn in next 30 days after FEATURE_DATE?
CREATE OR REPLACE TABLE RAW.CUSTOMER_OUTCOMES (
  CUSTOMER_ID VARCHAR,
  OUTCOME_DATE DATE,     -- date the outcome is defined (e.g., FEATURE_DATE)
  IS_CHURN BOOLEAN
);

-- Example insertion for demonstration (derive from transactions)
INSERT INTO RAW.CUSTOMER_OUTCOMES (CUSTOMER_ID, OUTCOME_DATE, IS_CHURN)
SELECT
  cf.CUSTOMER_ID,
  cf.FEATURE_DATE AS OUTCOME_DATE,
  CASE WHEN MAX(t.TX_TS) OVER (PARTITION BY cf.CUSTOMER_ID) <= DATEADD(day, 30, cf.FEATURE_DATE) THEN FALSE
       ELSE FALSE END -- placeholder; for real label define correctly
FROM FEATURE_STORE.CUSTOMER_FEATURES cf
LEFT JOIN RAW.TRANSACTIONS t
  ON cf.CUSTOMER_ID = t.CUSTOMER_ID;

CREATE OR REPLACE TABLE ML.TRAINING_CUSTOMER_DATA AS
SELECT
  f.FEATURE_DATE,
  f.CUSTOMER_ID,
  f.TX_COUNT_30D,
  f.TX_SUM_30D,
  f.TX_AVG_30D,
  f.TX_COUNT_90D,
  f.DAYS_SINCE_LAST_TX,
  f.IS_ACTIVE_30D,
  f.COUNTRY_TX_COUNT,
  f.SIGNUP_AGE_DAYS,
  f.IS_PREMIUM,
  COALESCE(o.IS_CHURN, FALSE) AS IS_CHURN
FROM FEATURE_STORE.CUSTOMER_FEATURES f
LEFT JOIN RAW.CUSTOMER_OUTCOMES o
  ON f.CUSTOMER_ID = o.CUSTOMER_ID AND f.FEATURE_DATE = o.OUTCOME_DATE;

SELECT FEATURE_DATE, COUNT(*) FROM FEATURE_STORE.CUSTOMER_FEATURES GROUP BY FEATURE_DATE;
SELECT
  SUM(CASE WHEN TX_COUNT_30D IS NULL THEN 1 ELSE 0 END) AS null_tx_count_30d,
  SUM(CASE WHEN TX_SUM_30D IS NULL THEN 1 ELSE 0 END) AS null_tx_sum_30d
FROM FEATURE_STORE.CUSTOMER_FEATURES;
SELECT TX_COUNT_30D, COUNT(*) FROM FEATURE_STORE.CUSTOMER_FEATURES GROUP BY TX_COUNT_30D ORDER BY TX_COUNT_30D;
